spring:
  # datasource configuration
  datasource:
    druid:
      url: jdbc:mysql://gz-cdb-drh06wqx.sql.tencentcdb.com:57613/insurance?serverTimeZone=UTC
      username: lingbomanbu
      password: Lyl14786632348
      initial-size: 100
      max-active: 100
      max-wait: 10000
      test-on-borrow: false
      test-on-return: false
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
# mybatis-plus configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
